apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: lowcode  # Specify the namespace here
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: sathish8329/proengageauth:11
        ports:
        - containerPort: 8080
        readinessProbe:  # Add readiness probe here
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 180
          periodSeconds: 10
          failureThreshold: 3  # Set failure threshold to 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1


---

apiVersion: v1
kind: Service
metadata:
  name: lowcode-auth-service
  namespace: lowcode  # Specify the namespace here
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
