apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: lowcode  # Specify the namespace here
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: sathish8329/proengageauth:13
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /api
            port: 8080
          initialDelaySeconds: 180
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3

---

apiVersion: v1
kind: Service
metadata:
  name: lowcode-auth-service
  namespace: lowcode  # Specify the namespace here
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
