apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: lowcode
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: prod-private
      containers:
      - name: api
        image: sathish8329/proengageback:4266
        ports:
        - containerPort: 8000
        # resources:                    # ← MOVE THIS INSIDE THE CONTAINER
        #   requests:
        #     cpu: 1000m
        #     memory: 1Gi
        #   limits:
        #     cpu: 500m
        #     memory: 2Gi
        livenessProbe:
          httpGet:
            path: /api
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
         

---

apiVersion: v1
kind: Service
metadata:
  name: lowcode-api-service
  namespace: lowcode  # Specify the namespace here
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
