apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: lowcode  # Specify the namespace here
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: sathish8329/proengageback:3
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /api   # Change this path based on your application's health check endpoint
            port: 8000   # Port where your application is listening
          initialDelaySeconds:  180 # Delay before first probe
          periodSeconds: 10         # How often to perform the probe
          failureThreshold: 3

---

apiVersion: v1
kind: Service
metadata:
  name: lowcode-api-service
  namespace: lowcode  # Specify the namespace here
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
