apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lowcode-ingress
  namespace: lowcode
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m" # Set the maximum allowed request body size to 100 MB
spec:
  rules:
  - host: "*.kovaion.ai"
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: lowcode-api-service
            port:
              number: 8000
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: lowcode-auth-service
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lowcode-frontend-service
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lowcode-ingress-https
  namespace: lowcode
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m" # Set the maximum allowed request body size to 100 MB
spec:
  rules:
  - host: "varahi.lionsms.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lowcode-frontend-service
            port:
              number: 80
  tls:
  - hosts:
    - varahi.lionsms.com
    secretName: varahi-lowcode-lionsms-com-tls

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: engage-ingress-https
  namespace: lowcode
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m" # Set the maximum allowed request body size to 100 MB
spec:
  rules:
  - host: "engage.kovaion.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lowcode-frontend-service
            port:
              number: 80
  tls:
  - hosts:
    - engage.kovaion.com
    secretName: engage-engage-kovaion-com-tls

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lowcode-ingress-kovaion-ai
  namespace: lowcode
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m" # Set the maximum allowed request body size to 100 MB
spec:
  rules:
  - host: "kovaion.ai"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lowcode-frontend-service
            port:
              number: 80
