node {
    def app

    stage('Clone repository') {
      

        checkout scm
    }

    stage('Update GIT') {
            script {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    withCredentials([usernamePassword(credentialsId: 'github', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        //def encodedPassword = URLEncoder.encode("$GIT_PASSWORD",'UTF-8')
                        sh "git config user.email sathish8329@gmail.com"
                        sh "git config user.name Sathish8329"
                        //sh "git switch master"
                        sh "cat backend.yaml"
                        sh "sed -i 's+sathish8329/proengageback.*+sathish8329/proengageback:${DOCKERTAG}+g' backend.yaml"
                        sh "cat backend.yaml"
                        sh "git add ."
                        sh "git commit -m 'Done by Jenkins Job changemanifest: ${env.BUILD_NUMBER}'"
                        sh "git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/${GIT_USERNAME}/prodlive.git HEAD:main"
      }
    }
  }
}
}
